version: "3.5"

services:
  postgres:
    container_name: cnmc-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      # POSTGRES_DB: ${POSTGRES_DB:-carbondata-test}
    ports:
      - "8321:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: cnmc-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5151:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
