name: cnmc
version: 0.1.0.0
github: "githubuser/cnmc"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2019 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/cnmc#readme>
default-extensions:
  - ViewPatterns
  - OverloadedStrings
  - DataKinds
  - TypeOperators
  - DeriveAnyClass
  - DeriveGeneric
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - TemplateHaskell
  - NamedFieldPuns

  # Deriving extensions
  - GeneralizedNewtypeDeriving
  - DeriveGeneric

dependencies:
  - base >= 4.7 && < 5
  - servant
  - servant-server
  - servant-client
  - servant-swagger
  - swagger2
  - time
  - text
  - wai
  - aeson
  - aeson-pretty
  - warp
  - wai-logger
  - opaleye
  - postgresql-simple
  - profunctors
  - product-profunctors
  - uuid
  - network-uri
  - hspec
  - extra
  - HUnit
  - containers
  - envy
  - req
  - http-client
  - http-client-tls
  - bytestring
  - lens

library:
  source-dirs: src

executables:
  cnmc-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cnmc

tests:
  cnmc-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded
      -rtsopts
      -with-rtsopts=-N
    dependencies:
      - cnmc
